services:
    php:
        build:
            context: .docker/php
            target: php_${PHP_TARGET}
        entrypoint: /usr/local/bin/php
        working_dir: $PWD
        volumes:
            -   $PWD:$PWD
        user: $uid:$gid

    apache:
        build:
            context: .docker/php
            target: php_${PHP_TARGET}
        volumes:
            -   $PWD:/var/www
        user: $uid:$gid
        ports:
            - "${PORT:-8080}:80"

    composer:
        build:
            context: .docker/php
            target: php_composer
        working_dir: $PWD
        environment:
            SSH_AUTH_SOCK: /tmp/auth.sock
        volumes:
            - $PWD:$PWD
            - $HOME/.composer/cache:/composer-cache
            - $HOME/.composer:/composer-home
            - $HOME/.ssh/known_hosts:/root/.ssh/known_hosts
            - $SSH_AUTH_SOCK:/tmp/auth.sock
        # When the `composer` container is run as a non-root user, the ssh client (used by `git clone`)
        # bails out when it is unable to detect a username. We cannot, however, add a user in the Dockerfile
        # since the actual UID is runtime-dependent. Creating the user in an entrypoint script is not possible
        # when the container is not running as root. So, for the time being, run this container as root.
        #user: $uid:$gid
        init: true

    node:
        build:
            context: .docker/node
            target: node_base
        working_dir: $PWD
        volumes:
            -   $PWD:$PWD
        user: $uid:$gid

    yarn:
        build:
            context: .docker/node
            target: node_yarn
        working_dir: $PWD
        volumes:
            - $PWD:$PWD
            - yarn_cache:/yarn-cache
        user: $uid:$gid

volumes:
    yarn_cache:
