services:
    php:
        build:
            context: .docker/php
            target: php_${PHP_TARGET}
        entrypoint: /usr/local/bin/php
        working_dir: $PWD
        volumes:
            -   $PWD:$PWD
        user: $uid:$gid

    apache:
        build:
            context: .docker/php
            target: php_${PHP_TARGET}
        volumes:
            -   $PWD:/var/www
        user: $uid:$gid
        ports:
            - "${PORT:-8080}:80"

    composer:
        build:
            context: .docker/php
            target: php_composer
        working_dir: $PWD
        volumes:
            - $PWD:$PWD
            - $HOME/.cache/composer:/composer-cache
            - $HOME/.config/composer:/composer-home
            - $SSH_AUTH_SOCK:/tmp/auth.sock
        user: $uid:$gid
        init: true

    node:
        build:
            context: .docker/node
            target: node_base
        working_dir: $PWD
        volumes:
            -   $PWD:$PWD
        user: $uid:$gid

    yarn:
        build:
            context: .docker/node
            target: node_yarn
        working_dir: $PWD
        volumes:
            - $PWD:$PWD
            - yarn_cache:/yarn-cache
        user: $uid:$gid

volumes:
    yarn_cache:
