version: "3.4"
services:
    php:
        build:
            context: .docker/php
            target: php_base
        working_dir: $PWD
        volumes:
            -   $PWD:$PWD
        user: $UID:$GID

    composer:
        build:
            context: .docker/php
            target: php_composer
        working_dir: $PWD
        volumes:
            -   $PWD:$PWD
        user: $UID:$GID
